Atualiza wiki com conteúdos faltantes
apyb/wiki pull request #30
Opened 2024-07-07 21:43 UTC by naanadr

2024-07-11 18:19 UTC, itepifanio commented
@naanadr seria legal adicionar [a chave pix aqui](https://apyb.python.org.br/associados/guias/como-organizar-eventos/#quais-sao-os-dados-da-pessoa-juridica-da-apyb)

2024-07-20 17:59 UTC, naanadr commented
> @naanadr seria legal adicionar [a chave pix aqui](https://apyb.python.org.br/associados/guias/como-organizar-eventos/#quais-sao-os-dados-da-pessoa-juridica-da-apyb)

não entendi a sugestão @itepifanio , seria para que recebamos doações por pix? Porque se sim, por motivos fiscais a gente não pode ter dinheiro entrando sem um mínimo de controle, então caso desejem fazer doações para a APyB o mais correto é entrar em contato.

2024-07-20 23:20 UTC, itepifanio commented
@naanadr a ideia não seria de doação. Normalmente os patrocinadores tem preferido realizar o pagamento via PIX, então ter a chave em algum lugar da Wiki seria útil.

2024-07-23 14:42 UTC, cecivieira commented
@itepifanio a nossa chave PIX é o CNPJ. 
Enquanto empresa não podemos aceitar doações aleatórias sem que haja algum tipo de registro.

2024-07-23 14:44 UTC, cecivieira commented on source/apyb/premio-dorneles-tremea-jean-ferri.md
> +**O Prêmio Dorneles Treméa/Jean Ferri é concedido a pessoa membra ou as pessoas membras da comunidade Python brasileira que mantêm vivo o espírito de colaboração, empreendedorismo e entrega à comunid
Sugiro inclusão da periodicidade de entrega do prêmio:

**O Prêmio Dorneles Treméa/Jean Ferri é concedido anualmente a pessoa membra ou as pessoas membras da comunidade Python brasileira que mantêm vivo o espírito de colaboração, empreendedorismo e entrega à comunidade.**

2024-07-23 14:45 UTC, cecivieira commented on source/infraestrutura/domínios.md
>  - [2023.pythonbrasil.org.br](https://2023.pythonbrasil.org.br): Edição 2023 da Python Brasil
Sugiro inserção do repositório com os dados das edições:
https://github.com/pythonbrasil/dados

2024-07-23 14:46 UTC, cecivieira requested changes
Comentários realizados no código.

2024-08-06 01:22 UTC, tiidadavena commented on source/a-associacao/comunicacao.md
>  - [Instagram](https://www.instagram.com/associacaopythonbrasil/)
```suggestion
- [Instagram](https://www.instagram.com/associacaopythonbrasil/)
- [LinkedIn](https://www.linkedin.com/company/associa%C3%A7%C3%A3o-python-brasil-apyb)
- [Mastodon](https://mastodon.social/@apyb)
- [E outros](https://linktr.ee/apyb)
```

2024-08-06 01:23 UTC, tiidadavena commented on source/a-associacao/comunicacao.md
> +- Lista de email exclusiva para associados: *apyb-associados[at]googlegroups.com*
```suggestion
- Lista de email exclusiva para pessoas associadas: *apyb-associados[at]googlegroups.com*
```

2024-08-06 01:23 UTC, tiidadavena commented on source/a-associacao/comunicacao.md
> +- *contato[at]python.org.br*
Excelente ponto!

2024-08-06 01:23 UTC, tiidadavena commented on source/a-associacao/financeiro.md
> +> Qualquer dúvida, entre em contato com a diretoria da APyB através do e-mail `diretoria[at]python.org.br`.
```suggestion
> Qualquer dúvida, entre em contato com a diretoria da APyB através do e-mail: `diretoria[at]python.org.br`.
```

2024-08-06 01:24 UTC, tiidadavena commented on source/a-associacao/financeiro.md
> +Prezamos pela transparência, e pensando nisso, disponibilizamos de forma aberto os nossos extratos bancários e o nosso balanço financeiro.
```suggestion
Prezamos pela transparência e colaboração da comunidade, e pensando nisso, disponibilizamos de forma aberta os nossos extratos bancários e o nosso balanço financeiro.
```

2024-08-06 01:25 UTC, tiidadavena commented on source/apyb/premio-dorneles-tremea-jean-ferri.md
> +**O Prêmio Dorneles Treméa/Jean Ferri é concedido a pessoa membra ou as pessoas membras da comunidade Python brasileira que mantêm vivo o espírito de colaboração, empreendedorismo e entrega à comunid
```suggestion
**O Prêmio Dorneles Treméa/Jean Ferri é concedido anualmente à pessoa membra ou às pessoas membras da comunidade Python brasileira que mantêm vivo o espírito de colaboração, empreendedorismo e entrega à comunidade. As indicações são feitas pela comunidade e a Cerimônia de Entrega ocorre durante a Python Brasil.**
```

2024-08-06 01:26 UTC, tiidadavena commented on source/infraestrutura/domínios.md
> +- [talks.python.org.br](https://talks.python.org.br): Servidor do pretalx mantido pela comunidade Python brasileira
```suggestion
- [talks.python.org.br](https://talks.python.org.br): Servidor da plataforma de submissão de palestras Pretalx mantido pela comunidade Python brasileira.
```

2024-08-06 01:27 UTC, tiidadavena reviewed
Apenas alguns detalhes, mas após as resoluções deles, pode dale

2024-08-06 01:35 UTC, tiidadavena commented
> [PR Preview Action](https://github.com/rossjrw/pr-preview-action) v1.4.7
> 🚀 Deployed preview to https://apyb.github.io/wiki/pr-preview/pr-30/
> on branch [`gh-pages`](https://github.com/apyb/wiki/tree/gh-pages) at 2024-07-07 21:43 UTC

O preview da página estática não está funcionando

2024-08-09 00:51 UTC, naanadr commented on source/infraestrutura/domínios.md
>  - [2023.pythonbrasil.org.br](https://2023.pythonbrasil.org.br): Edição 2023 da Python Brasil
Ele já está na [lista de repositórios](https://apyb.python.org.br/infraestrutura/reposit%C3%B3rios/#python-brasil). 
![image](https://github.com/user-attachments/assets/6254487c-d36c-4c84-9693-635a5f93cd2e)

2024-08-09 00:52 UTC, merged